export const iPhoneKeywords = [
  { keyword: 'iphone 16', model: 'Apple iPhone 16' },
  { keyword: 'iphone 16 plus', model: 'Apple iPhone 16 Plus' },
  { keyword: 'iphone 16 pro', model: 'Apple iPhone 16 Pro' },
  { keyword: 'iphone 16 pro max', model: 'Apple iPhone 16 Pro Max' },
  { keyword: 'iphone 15', model: 'Apple iPhone 15' },
  { keyword: 'iphone 15 plus', model: 'Apple iPhone 15 Plus' },
  { keyword: 'iphone 15 pro', model: 'Apple iPhone 15 Pro' },
  { keyword: 'iphone 15 pro max', model: 'Apple iPhone 15 Pro Max' },
  { keyword: 'iphone 14', model: 'Apple iPhone 14' },
  { keyword: 'iphone 14 plus', model: 'Apple iPhone 14 Plus' },
  { keyword: 'iphone 14 pro', model: 'Apple iPhone 14 Pro' },
  { keyword: 'iphone 14 pro max', model: 'Apple iPhone 14 Pro Max' },
  { keyword: 'iphone 13', model: 'Apple iPhone 13' },
  { keyword: 'iphone 13 pro', model: 'Apple iPhone 13 Pro' },
  { keyword: 'iphone 13 pro max', model: 'Apple iPhone 13 Pro Max' },
  { keyword: 'iphone 13 mini', model: 'Apple iPhone 13 mini' },
  { keyword: 'iphone 12', model: 'Apple iPhone 12' },
  { keyword: 'iphone 12 pro', model: 'Apple iPhone 12 Pro' },
  { keyword: 'iphone 12 pro max', model: 'Apple iPhone 12 Pro Max' },
  { keyword: 'iphone 12 mini', model: 'Apple iPhone 12 mini' },
  { keyword: 'iphone 11', model: 'Apple iPhone 11' },
  { keyword: 'iphone 11 pro', model: 'Apple iPhone 11 Pro' },
  { keyword: 'iphone 11 pro max', model: 'Apple iPhone 11 Pro Max' },
  { keyword: 'iphone x', model: 'Apple iPhone X' },
  { keyword: 'iphone xr', model: 'Apple iPhone XR' },
  { keyword: 'iphone xs', model: 'Apple iPhone XS' },
  { keyword: 'iphone xs max', model: 'Apple iPhone XS Max' }
]

export const galaxyKeywords = [
  { keyword: 'galaxy s25', model: 'Samsung Galaxy S25' },
  { keyword: 'galaxy s25 plus', model: 'Samsung Galaxy S25+' },
  { keyword: 'galaxy s25 ultra', model: 'Samsung Galaxy S25 Ultra' },
  { keyword: 'galaxy s24', model: 'Samsung Galaxy S24' },
  { keyword: 'galaxy s24 plus', model: 'Samsung Galaxy S24+' },
  { keyword: 'galaxy s24 ultra', model: 'Samsung Galaxy S24 Ultra' },
  { keyword: 'galaxy s23', model: 'Samsung Galaxy S23' },
  { keyword: 'galaxy s23 plus', model: 'Samsung Galaxy S23+' },
  { keyword: 'galaxy s23 ultra', model: 'Samsung Galaxy S23 Ultra' },
  { keyword: 'galaxy s22', model: 'Samsung Galaxy S22' },
  { keyword: 'galaxy s22 plus', model: 'Samsung Galaxy S22+' },
  { keyword: 'galaxy s22 ultra', model: 'Samsung Galaxy S22 Ultra' },
  { keyword: 'galaxy s21', model: 'Samsung Galaxy S21' },
  { keyword: 'galaxy s21 plus', model: 'Samsung Galaxy S21+' },
  { keyword: 'galaxy s21 ultra', model: 'Samsung Galaxy S21 Ultra' },
  { keyword: 'galaxy s20', model: 'Samsung Galaxy S20 5G' },
  { keyword: 'galaxy s20 plus', model: 'Samsung Galaxy S20+' },
  { keyword: 'galaxy s20 ultra', model: 'Samsung Galaxy S20 Ultra' },
  { keyword: 'galaxy s10', model: 'Samsung Galaxy S10' },
  { keyword: 'galaxy s10 plus', model: 'Samsung Galaxy S10+' },
  { keyword: 'galaxy s10e', model: 'Samsung Galaxy S10e' },
  { keyword: 'galaxy s24 fe', model: 'Samsung Galaxy S24 FE' },
  { keyword: 'galaxy s23 fe', model: 'Samsung Galaxy S23 FE' },
  { keyword: 'galaxy s21 fe', model: 'Samsung Galaxy S21 FE 5G' },
  { keyword: 'galaxy s20 fe', model: 'Samsung Galaxy S20 FE 5G' },
  { keyword: 'galaxy note 20', model: 'Samsung Galaxy Note 20 5G' },
  { keyword: 'galaxy note 20 ultra', model: 'Samsung Galaxy Note20 Ultra 5G' }, //
  { keyword: 'galaxy note 10', model: 'Samsung Galaxy Note10' },
  { keyword: 'galaxy note 10 plus', model: 'Samsung Galaxy Note10+ 5G' },
  { keyword: 'galaxy z flip 6', model: 'Samsung Galaxy Z Flip6' },
  { keyword: 'galaxy z flip 5', model: 'Samsung Galaxy Z Flip5' },
  { keyword: 'galaxy z flip 4', model: 'Samsung Galaxy Z Flip4' },
  { keyword: 'galaxy z flip 3', model: 'Samsung Galaxy Z Flip3' },
  { keyword: 'galaxy z fold 6', model: 'Samsung Galaxy Z Fold6' },
  { keyword: 'galaxy z fold 5', model: 'Samsung Galaxy Z Fold5' },
  { keyword: 'galaxy z fold 4', model: 'Samsung Galaxy Z Fold4' },
  { keyword: 'galaxy z fold 3', model: 'Samsung Galaxy Z Fold3' },
  { keyword: 'galaxy a74', model: 'Samsung Galaxy A74' },
  { keyword: 'galaxy a73', model: 'Samsung Galaxy A73 5G' },
  { keyword: 'galaxy a72', model: 'Samsung Galaxy A72' },
  { keyword: 'galaxy a71', model: 'Samsung Galaxy A71' },
  { keyword: 'galaxy a54', model: 'Samsung Galaxy A54' },
  { keyword: 'galaxy a53', model: 'Samsung Galaxy A53 5G' },
  { keyword: 'galaxy a52', model: 'Samsung Galaxy A52' },
  { keyword: 'galaxy a51', model: 'Samsung Galaxy A51' },
  { keyword: 'galaxy a33', model: 'Samsung Galaxy A33 5G' },
  { keyword: 'galaxy a32', model: 'Samsung Galaxy A32' },
  { keyword: 'galaxy a31', model: 'Samsung Galaxy A31' },
  { keyword: 'galaxy a30', model: 'Samsung Galaxy A30' }
]

export const galaxyKeywordsFB = [
  { keyword: 'galaxy s25', model: 'Samsung Galaxy S25' },
  { keyword: 'galaxy s25 plus', model: 'Samsung Galaxy S25+' },
  { keyword: 'galaxy s25 ultra', model: 'Samsung Galaxy S25 Ultra' },
  { keyword: 'galaxy s24', model: 'Samsung Galaxy S24' },
  { keyword: 'galaxy s24 plus', model: 'Samsung Galaxy S24+' },
  { keyword: 'galaxy s24 ultra', model: 'Samsung Galaxy S24 Ultra' },
  { keyword: 'galaxy s23', model: 'Samsung Galaxy S23' },
  { keyword: 'galaxy s23 plus', model: 'Samsung Galaxy S23+' },
  { keyword: 'galaxy s23 ultra', model: 'Samsung Galaxy S23 Ultra' },
  { keyword: 'galaxy s22', model: 'Samsung Galaxy S22' },
  { keyword: 'galaxy s22 plus', model: 'Samsung Galaxy S22+' },
  { keyword: 'galaxy s22 ultra', model: 'Samsung Galaxy S22 Ultra' },
  { keyword: 'galaxy s21', model: 'Samsung Galaxy S21' },
  { keyword: 'galaxy s21 plus', model: 'Samsung Galaxy S21+' },
  { keyword: 'galaxy s21 ultra', model: 'Samsung Galaxy S21 Ultra' },
  { keyword: 'galaxy s20', model: 'Samsung Galaxy S20 5G' },
  { keyword: 'galaxy s20 plus', model: 'Samsung Galaxy S20+' },
  { keyword: 'galaxy s20 ultra', model: 'Samsung Galaxy S20 Ultra' },
  { keyword: 'galaxy s10', model: 'Samsung Galaxy S10' },
  { keyword: 'galaxy s10 plus', model: 'Samsung Galaxy S10+' },
  { keyword: 'galaxy s10e', model: 'Samsung Galaxy S10e' },
  { keyword: 'galaxy s24 fe', model: 'Samsung Galaxy S24 FE' },
  { keyword: 'galaxy s23 fe', model: 'Samsung Galaxy S23 FE' },
  { keyword: 'galaxy s21 fe', model: 'Samsung Galaxy S21 FE 5G' },
  { keyword: 'galaxy s20 fe', model: 'Samsung Galaxy S20 FE 5G' }
]
